 # 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
x=np.zeros(10)
x[4]=1
print("Null Vector of size 10 but the 5th value is 1 :\n", x)

Null Vector of size 10 but the 5th value is 1 :
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 # 2. Create a vector with values ranging from 10 to 49.

In [2]:
v = np.arange(10,49)
print("Vector with values ranging from 10 to 49 :\n", v)

Vector with values ranging from 10 to 49 :
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
a = np.array([1,2,0,0,4,0])
np.where(a > 0)

(array([0, 1, 4], dtype=int64),)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
b = np.random.random((10,10))
print("Original Array : \n", b)
bmin, bmax = b.min(), b.max()
print("Minimum and Maximum Values : \n", bmin, bmax)


Original Array : 
 [[0.55337543 0.60884175 0.16741702 0.29104585 0.84948679 0.63757409
  0.87194611 0.94234358 0.66977368 0.39861281]
 [0.78596064 0.94791645 0.61665771 0.08853363 0.18086823 0.33312027
  0.34297444 0.80716907 0.23721562 0.57009306]
 [0.1465365  0.12467151 0.4544558  0.45309182 0.03357464 0.45297582
  0.44529638 0.17621064 0.21300782 0.56949815]
 [0.64153181 0.81947536 0.70752165 0.12461642 0.52318597 0.32715609
  0.01954978 0.42134722 0.72626152 0.36808486]
 [0.27454629 0.71754084 0.20006386 0.37797307 0.51577714 0.17766008
  0.99785089 0.90264905 0.51766915 0.12748168]
 [0.1364614  0.38262509 0.3656722  0.50705089 0.06265235 0.89082012
  0.45681198 0.27619394 0.22445261 0.14201668]
 [0.11886982 0.97803728 0.234562   0.33434278 0.62320291 0.97091819
  0.04762553 0.50884831 0.01216362 0.67735042]
 [0.78399867 0.73424046 0.86372442 0.17279013 0.64842831 0.64918207
  0.39503731 0.51452043 0.18618474 0.77910171]
 [0.37132694 0.44699238 0.05078796 0.66890278 0.32705328 0.59

# 6. Create a random vector of size 30 and find the mean value.

In [6]:
c = np.random.random(30)
print("Original array : \n", c)
print("Mean Value : \n", np.mean(c))

Original array : 
 [0.44867763 0.35635834 0.42213743 0.3622015  0.34265935 0.80857971
 0.66463161 0.15345599 0.64417259 0.66682819 0.92217351 0.77074077
 0.38621789 0.8580512  0.57812048 0.87365107 0.77892335 0.75468855
 0.74509394 0.81844607 0.05234527 0.0277327  0.81408436 0.92091189
 0.74512148 0.89778193 0.70363483 0.04810454 0.72105823 0.07070394]
Mean Value : 
 0.578576277739972
